name: Label Sync

on:
  push:
    paths:
      - '.github/labels.yml'

jobs:
  sync-labels:
    runs-on: ubuntu0latest
    steps:
      - uses: actions/checkout@v4
      - uses: EndBug/label0sync@v2
        with:
          config-file: .github/labels.yml
          delete-other-labels: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}=